In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sys
customized_path_to_homework = "/content/drive/MyDrive/Masters/VTech Subjects/CS 5834 Intro to Urban Computing/Project/code/Urban Dataset"
sys.path.append(customized_path_to_homework)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Masters/VTech Subjects/CS 5834 Intro to Urban Computing/Project/code/UrbanProject_R1.xlsx')
df.head(5)

   unique_id  ...  Ranking (using National Standards -- NAAQS)
0     315585  ...                                           A+
1     130728  ...                                            B
2     315633  ...                                            B
3     130776  ...                                            D
4     605648  ...                                            B

[5 rows x 15 columns]

In [ ]:
df.shape

(11449, 15)

In [ ]:
df1 = df.loc[df["time_period"] == 2011]
df1.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
0       315585  ...                                           A+
2       315633  ...                                            B
83      315586  ...                                            A
85      315634  ...                                            B
166     315587  ...                                            A
168     315635  ...                                            C
249     315588  ...                                            A
251     315636  ...                                            B
332     315589  ...                                           A+
334     315637  ...                                            B

[10 rows x 15 columns]

In [ ]:
df2 = df.loc[df["time_period"] == "Annual Average 2011"]
df2.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
25      179653  ...                                            C
53      179428  ...                                            A
106     179654  ...                                            C
135     179429  ...                                            A
190     179655  ...                                            C
223     179430  ...                                            B
272     179656  ...                                            C
301     179431  ...                                            A
356     179657  ...                                            C
380     179432  ...                                            A

[10 rows x 15 columns]

In [ ]:
df3 = df.loc[df["time_period"] == "Summer 2011"]
df3.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
29      179578  ...                                            C
42      179353  ...                                            A
71      219967  ...                                            A
112     179579  ...                                            C
125     179354  ...                                            A
154     219973  ...                                            A
195     179580  ...                                            D
213     179355  ...                                            B
235     219979  ...                                            A
278     179581  ...                                            C

[10 rows x 15 columns]

In [ ]:
df4 = df.loc[df["time_period"] == "Winter 2010-11"]
df4.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
32      179503  ...                                            D
62      179278  ...                                            B
81      179203  ...                                           A+
115     179504  ...                                            D
146     179279  ...                                            B
164     179204  ...                                           A+
198     179505  ...                                            D
228     179280  ...                                            B
247     179205  ...                                           A+
281     179506  ...                                            D

[10 rows x 15 columns]

In [ ]:
df = pd.concat([df1, df2, df3, df4], axis=0, ignore_index=True)

In [ ]:
df.head()

   unique_id  ...  Ranking (using National Standards -- NAAQS)
0     315585  ...                                           A+
1     315633  ...                                            B
2     315586  ...                                            A
3     315634  ...                                            B
4     315587  ...                                            A

[5 rows x 15 columns]

In [ ]:
df.shape

(1342, 15)

In [ ]:
df.drop('measure', axis=1, inplace=True)
df.drop('measure_info', axis=1, inplace=True)
df.drop('data_value (units vary)', axis=1, inplace=True)
df.drop('start_date', axis=1, inplace=True)
df.insert(3, 'measure', "Annual Average Concentration")
df.insert(4, 'measure_info', "µg/m3")

In [ ]:
df.head()

   unique_id  ...  Ranking (using National Standards -- NAAQS)
0     315585  ...                                           A+
1     315633  ...                                            B
2     315586  ...                                            A
3     315634  ...                                            B
4     315587  ...                                            A

[5 rows x 13 columns]

In [ ]:
df1 = df.loc[df["time_period"] == 2011]
df1.head(10)

   unique_id  ...  Ranking (using National Standards -- NAAQS)
0     315585  ...                                           A+
1     315633  ...                                            B
2     315586  ...                                            A
3     315634  ...                                            B
4     315587  ...                                            A
5     315635  ...                                            C
6     315588  ...                                            A
7     315636  ...                                            B
8     315589  ...                                           A+
9     315637  ...                                            B

[10 rows x 13 columns]

In [ ]:
df2 = df.loc[df["time_period"] == "Annual Average 2011"]
df2.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
214     179653  ...                                            C
215     179428  ...                                            A
216     179654  ...                                            C
217     179429  ...                                            A
218     179655  ...                                            C
219     179430  ...                                            B
220     179656  ...                                            C
221     179431  ...                                            A
222     179657  ...                                            C
223     179432  ...                                            A

[10 rows x 13 columns]

In [ ]:
df3 = df.loc[(df["time_period"] == "Summer 2011") & (df["name"] == "Ozone (O3)")]
df3.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
498     219967  ...                                            A
501     219973  ...                                            A
504     219979  ...                                            A
507     219985  ...                                            A
510     219991  ...                                            A
513     216280  ...                                            A
516     216286  ...                                            A
519     216292  ...                                            A
522     216298  ...                                            A
525     216304  ...                                            A

[10 rows x 13 columns]

In [ ]:
df4 = df.loc[(df["time_period"] == "Winter 2010-11") & (df["name"] == "Sulfur Dioxide (SO2)")]
df4.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
921     179203  ...                                           A+
924     179204  ...                                           A+
927     179205  ...                                           A+
930     179206  ...                                           A+
933     179207  ...                                           A+
936     164972  ...                                           A+
939     164973  ...                                           A+
942     164974  ...                                           A+
945     164975  ...                                           A+
948     164976  ...                                           A+

[10 rows x 13 columns]

In [ ]:
df = pd.concat([df1, df2, df3, df4], axis=0, ignore_index=True)

In [ ]:
df.drop('time_period', axis=1, inplace=True)
df.insert(9, 'time_period', 2011)
df.head(10)

   unique_id  ...  Ranking (using National Standards -- NAAQS)
0     315585  ...                                           A+
1     315633  ...                                            B
2     315586  ...                                            A
3     315634  ...                                            B
4     315587  ...                                            A
5     315635  ...                                            C
6     315588  ...                                            A
7     315636  ...                                            B
8     315589  ...                                           A+
9     315637  ...                                            B

[10 rows x 13 columns]

In [ ]:
df10 = df.loc[df["name"] == "Air Toxics Concentrations- Average Benzene Concentrations"]
df10.head(10)

    unique_id  ...  Ranking (using National Standards -- NAAQS)
0      315585  ...                                           A+
2      315586  ...                                            A
4      315587  ...                                            A
6      315588  ...                                            A
8      315589  ...                                           A+
10     227568  ...                                            A
12     227569  ...                                            B
14     227570  ...                                            A
16     227571  ...                                            B
18     227572  ...                                            B

[10 rows x 13 columns]

In [ ]:
df11 = df.loc[df["name"] == "Air Toxics Concentrations- Average Formaldehyde Concentrations"]
df11.head(10)

    unique_id  ...  Ranking (using National Standards -- NAAQS)
1      315633  ...                                            B
3      315634  ...                                            B
5      315635  ...                                            C
7      315636  ...                                            B
9      315637  ...                                            B
11     227509  ...                                            C
13     227510  ...                                            C
15     227511  ...                                            C
17     227512  ...                                            C
19     227513  ...                                            D

[10 rows x 13 columns]

In [ ]:
df12 = df.loc[df["name"] == "Fine Particulate Matter (PM2.5)"]
df12.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
214     179653  ...                                            C
216     179654  ...                                            C
218     179655  ...                                            C
220     179656  ...                                            C
222     179657  ...                                            C
224     170282  ...                                            D
226     170283  ...                                            D
228     170284  ...                                            C
230     170285  ...                                            D
232     170286  ...                                            D

[10 rows x 13 columns]

In [ ]:
df13 = df.loc[df["name"] == "Nitrogen Dioxide (NO2)"]
df13.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
215     179428  ...                                            A
217     179429  ...                                            A
219     179430  ...                                            B
221     179431  ...                                            A
223     179432  ...                                            A
225     167627  ...                                            B
227     167628  ...                                            B
229     167629  ...                                            B
231     167630  ...                                            B
233     167631  ...                                            C

[10 rows x 13 columns]

In [ ]:
df14 = df.loc[df["name"] == "Ozone (O3)"]
df14.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
496     219967  ...                                            A
497     219973  ...                                            A
498     219979  ...                                            A
499     219985  ...                                            A
500     219991  ...                                            A
501     216280  ...                                            A
502     216286  ...                                            A
503     216292  ...                                            A
504     216298  ...                                            A
505     216304  ...                                            A

[10 rows x 13 columns]

In [ ]:
df15 = df.loc[df["name"] == "Sulfur Dioxide (SO2)"]
df15.head(10)

     unique_id  ...  Ranking (using National Standards -- NAAQS)
637     179203  ...                                           A+
638     179204  ...                                           A+
639     179205  ...                                           A+
640     179206  ...                                           A+
641     179207  ...                                           A+
642     164972  ...                                           A+
643     164973  ...                                           A+
644     164974  ...                                           A+
645     164975  ...                                           A+
646     164976  ...                                           A+

[10 rows x 13 columns]

In [ ]:
df10.drop('name', axis=1, inplace=True)
df11.drop('name', axis=1, inplace=True)
df12.drop('name', axis=1, inplace=True)
df13.drop('name', axis=1, inplace=True)
df14.drop('name', axis=1, inplace=True)
df15.drop('name', axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df10.rename(columns={'data-value_µg/m3 (all converted to µg/m3)': 'Air Toxics Concentrations- Average Benzene Concentrations'}, inplace=True)
df10.rename(columns={'Ranking (using National Standards -- NAAQS)': 'Ranking of Average Benzene Concentrations'}, inplace=True)
df10.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

    unique_id  ...  Ranking of Average Benzene Concentrations
0      315585  ...                                         A+
2      315586  ...                                          A
4      315587  ...                                          A
6      315588  ...                                          A
8      315589  ...                                         A+
10     227568  ...                                          A
12     227569  ...                                          B
14     227570  ...                                          A
16     227571  ...                                          B
18     227572  ...                                          B

[10 rows x 12 columns]

In [ ]:
df11.rename(columns={'data-value_µg/m3 (all converted to µg/m3)': 'Air Toxics Concentrations- Average Formaldehyde Concentrations'}, inplace=True)
df11.rename(columns={'Ranking (using National Standards -- NAAQS)': 'Ranking of Average Formaldehyde Concentrations'}, inplace=True)
df11.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

    unique_id  ...  Ranking of Average Formaldehyde Concentrations
1      315633  ...                                               B
3      315634  ...                                               B
5      315635  ...                                               C
7      315636  ...                                               B
9      315637  ...                                               B
11     227509  ...                                               C
13     227510  ...                                               C
15     227511  ...                                               C
17     227512  ...                                               C
19     227513  ...                                               D

[10 rows x 12 columns]

In [ ]:
df12.rename(columns={'data-value_µg/m3 (all converted to µg/m3)': 'Fine Particulate Matter (PM2.5)'}, inplace=True)
df12.rename(columns={'Ranking (using National Standards -- NAAQS)': 'Ranking of Fine Particulate Matter (PM2.5)'}, inplace=True)
df12.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

     unique_id  ...  Ranking of Fine Particulate Matter (PM2.5)
214     179653  ...                                           C
216     179654  ...                                           C
218     179655  ...                                           C
220     179656  ...                                           C
222     179657  ...                                           C
224     170282  ...                                           D
226     170283  ...                                           D
228     170284  ...                                           C
230     170285  ...                                           D
232     170286  ...                                           D

[10 rows x 12 columns]

In [ ]:
df13.rename(columns={'data-value_µg/m3 (all converted to µg/m3)': 'Nitrogen Dioxide (NO2)'}, inplace=True)
df13.rename(columns={'Ranking (using National Standards -- NAAQS)': 'Ranking of Nitrogen Dioxide (NO2)'}, inplace=True)
df13.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

     unique_id  ...  Ranking of Nitrogen Dioxide (NO2)
215     179428  ...                                  A
217     179429  ...                                  A
219     179430  ...                                  B
221     179431  ...                                  A
223     179432  ...                                  A
225     167627  ...                                  B
227     167628  ...                                  B
229     167629  ...                                  B
231     167630  ...                                  B
233     167631  ...                                  C

[10 rows x 12 columns]

In [ ]:
df14.rename(columns={'data-value_µg/m3 (all converted to µg/m3)': 'Ozone (O3)'}, inplace=True)
df14.rename(columns={'Ranking (using National Standards -- NAAQS)': 'Ranking of Ozone (O3)'}, inplace=True)
df14.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

     unique_id  indicator_id  ... Ranking (using local-mean) Ranking of Ozone (O3)
496     219967           386  ...                          D                     A
497     219973           386  ...                          D                     A
498     219979           386  ...                          C                     A
499     219985           386  ...                          D                     A
500     219991           386  ...                          D                     A
501     216280           386  ...                          C                     A
502     216286           386  ...                          C                     A
503     216292           386  ...                          C                     A
504     216298           386  ...                          C                     A
505     216304           386  ...                          B                     A

[10 rows x 12 columns]

In [ ]:
df15.rename(columns={'data-value_µg/m3 (all converted to µg/m3)': 'Sulfur Dioxide (SO2)'}, inplace=True)
df15.rename(columns={'Ranking (using National Standards -- NAAQS)': 'Ranking of Sulfur Dioxide (SO2)'}, inplace=True)
df15.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

     unique_id  ...  Ranking of Sulfur Dioxide (SO2)
637     179203  ...                               A+
638     179204  ...                               A+
639     179205  ...                               A+
640     179206  ...                               A+
641     179207  ...                               A+
642     164972  ...                               A+
643     164973  ...                               A+
644     164974  ...                               A+
645     164975  ...                               A+
646     164976  ...                               A+

[10 rows x 12 columns]

In [ ]:
df10 = df10.merge(df11[['geo_place_name', 'Air Toxics Concentrations- Average Formaldehyde Concentrations']])

In [ ]:
df10 = df10.merge(df12[['geo_place_name', 'Fine Particulate Matter (PM2.5)']])

In [ ]:
df10 = df10.merge(df13[['geo_place_name', 'Nitrogen Dioxide (NO2)']])

In [ ]:
df10 = df10.merge(df14[['geo_place_name', 'Ozone (O3)']])

In [ ]:
df10 = df10.merge(df15[['geo_place_name', 'Sulfur Dioxide (SO2)']])

In [ ]:
df10 = df10.merge(df11[['geo_place_name', 'Ranking of Average Formaldehyde Concentrations']])

In [ ]:
df10 = df10.merge(df12[['geo_place_name', 'Ranking of Fine Particulate Matter (PM2.5)']])

In [ ]:
df10 = df10.merge(df13[['geo_place_name', 'Ranking of Nitrogen Dioxide (NO2)']])

In [ ]:
df10 = df10.merge(df14[['geo_place_name', 'Ranking of Ozone (O3)']])

In [ ]:
df10 = df10.merge(df15[['geo_place_name', 'Ranking of Sulfur Dioxide (SO2)']])

In [ ]:
df10.shape

(6992, 22)

In [ ]:
df10.drop('unique_id', axis=1, inplace=True)
df10.drop('indicator_id', axis=1, inplace=True)

In [ ]:
df10.head(10)

                        measure  ... Ranking of Sulfur Dioxide (SO2)
0  Annual Average Concentration  ...                              A+
1  Annual Average Concentration  ...                              A+
2  Annual Average Concentration  ...                              A+
3  Annual Average Concentration  ...                              A+
4  Annual Average Concentration  ...                              A+
5  Annual Average Concentration  ...                              A+
6  Annual Average Concentration  ...                              A+
7  Annual Average Concentration  ...                              A+
8  Annual Average Concentration  ...                              A+
9  Annual Average Concentration  ...                              A+

[10 rows x 20 columns]

In [ ]:
df = df10.iloc[:, [3,4,2,5,7,10,11,12,13,14,0,1,6,8,9,15,16,17,18,19]]

In [ ]:
df.head(10)

   geo_join_id  ... Ranking of Sulfur Dioxide (SO2)
0            1  ...                              A+
1            2  ...                              A+
2            3  ...                              A+
3            4  ...                              A+
4            5  ...                              A+
5          101  ...                              A+
6          102  ...                              A+
7          103  ...                              A+
8          104  ...                              A+
9          105  ...                              A+

[10 rows x 20 columns]

In [ ]:
df1 = df10.iloc[:, [9,15,16,17,18,19]]

In [ ]:
maxValuesObj = df1.max(axis=1)
df1["Final Ranking"]=maxValuesObj
df1.head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Ranking of Average Benzene Concentrations  ... Final Ranking
0                                        A+  ...             C
1                                         A  ...             C
2                                         A  ...             C
3                                         A  ...             C
4                                        A+  ...             C
5                                         A  ...             D
6                                         B  ...             D
7                                         A  ...             C
8                                         B  ...             D
9                                         B  ...             D

[10 rows x 7 columns]

In [ ]:
ranking = df1["Final Ranking"]
df = df.join(ranking)

In [ ]:
df.drop('Ranking (using local-mean)', axis=1, inplace=True)

In [ ]:
df.head(10)

   geo_join_id  ... Final Ranking
0            1  ...             C
1            2  ...             C
2            3  ...             C
3            4  ...             C
4            5  ...             C
5          101  ...             D
6          102  ...             D
7          103  ...             C
8          104  ...             D
9          105  ...             D

[10 rows x 20 columns]

In [ ]:
df.groupby(by=["Final Ranking"]).count()

               geo_join_id  ...  Ranking of Sulfur Dioxide (SO2)
Final Ranking               ...
B                      257  ...                              257
C                     6724  ...                             6724
D                       11  ...                               11

[3 rows x 19 columns]

In [ ]:
df.head()

   geo_join_id geo_place_name  ... Ranking of Sulfur Dioxide (SO2) Final Ranking
0            1          Bronx  ...                              A+             C
1            2       Brooklyn  ...                              A+             C
2            3      Manhattan  ...                              A+             C
3            4         Queens  ...                              A+             C
4            5  Staten Island  ...                              A+             C

[5 rows x 20 columns]

In [ ]:
df.to_excel("/content/drive/MyDrive/Masters/VTech Subjects/CS 5834 Intro to Urban Computing/Project/code/UrbanProject_R1_FR.xlsx")

In [ ]:
# train_columns = ["geo_place_name", "geo_type_name", "Ranking of Average Benzene Concentrations", "Ranking of Average Formaldehyde Concentrations", "Ranking of Fine Particulate Matter (PM2.5)", "Ranking of Nitrogen Dioxide (NO2)", "Ranking of Ozone (O3)", "Ranking of Sulfur Dioxide (SO2)", "Final Ranking"]

train_columns = ["geo_place_name", "geo_type_name", "geo_borough_name", "Air Toxics Concentrations- Average Benzene Concentrations", "Air Toxics Concentrations- Average Formaldehyde Concentrations", "Fine Particulate Matter (PM2.5)", "Nitrogen Dioxide (NO2)", "Ozone (O3)", "Sulfur Dioxide (SO2)", "Final Ranking"]

In [ ]:
df[train_columns].head(6)

             geo_place_name geo_type_name  ... Sulfur Dioxide (SO2)  Final Ranking
0                     Bronx       Borough  ...              14.2528              C
1                  Brooklyn       Borough  ...               8.5412              C
2                 Manhattan       Borough  ...              20.4098              C
3                    Queens       Borough  ...               8.9604              C
4             Staten Island       Borough  ...               4.6636              C
5  Financial District (CD1)            CD  ...              10.3752              D

[6 rows x 10 columns]

In [ ]:
df[train_columns].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6992 entries, 0 to 6991
Data columns (total 10 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   geo_place_name                                                  6992 non-null   object
 1   geo_type_name                                                   6992 non-null   object
 2   geo_borough_name                                                6992 non-null   object
 3   Air Toxics Concentrations- Average Benzene Concentrations       6992 non-null   float64
 4   Air Toxics Concentrations- Average Formaldehyde Concentrations  6992 non-null   float64
 5   Fine Particulate Matter (PM2.5)                                 6992 non-null   float64
 6   Nitrogen Dioxide (NO2)                                          6992 non-null   float64
 7   Ozone (O3)                                                      6992 non-null   float64
 8   Sulfur Dioxide (SO2)                                            6992 non-null   float64
 9   Final Ranking                                                   6992 non-null   object
dtypes: float64(6), object(4)
memory usage: 920.9+ KB

In [ ]:
trainset = df[train_columns].loc[(df["geo_borough_name"] != "Manhattan") ]

In [ ]:
trainset.head()

                  geo_place_name  ... Final Ranking
0                          Bronx  ...             C
1                       Brooklyn  ...             C
3                         Queens  ...             C
4                  Staten Island  ...             C
17  Mott Haven and Melrose (CD1)  ...             C

[5 rows x 10 columns]

In [ ]:
testset = df[train_columns].loc[df["geo_borough_name"] == "Manhattan"]

In [ ]:
testset.head()

                        geo_place_name  ... Final Ranking
2                            Manhattan  ...             C
5             Financial District (CD1)  ...             D
6     Greenwich Village and Soho (CD2)  ...             D
7  Lower East Side and Chinatown (CD3)  ...             C
8            Clinton and Chelsea (CD4)  ...             D

[5 rows x 10 columns]

In [ ]:
trainset.groupby(by=["Final Ranking"]).count()

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
B                         257            257  ...         257                   257
C                        5692           5692  ...        5692                  5692

[2 rows x 9 columns]

In [ ]:
testset.groupby(by=["Final Ranking"]).count()

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
C                        1032           1032  ...        1032                  1032
D                          11             11  ...          11                    11

[2 rows x 9 columns]

In [ ]:
display(trainset.groupby(by=["Final Ranking"]).count())
display(testset.groupby(by=["Final Ranking"]).count())
display(trainset)
display(testset)

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
B                         257            257  ...         257                   257
C                        5692           5692  ...        5692                  5692

[2 rows x 9 columns]

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
C                        1032           1032  ...        1032                  1032
D                          11             11  ...          11                    11

[2 rows x 9 columns]

                    geo_place_name  ... Final Ranking
0                            Bronx  ...             C
1                         Brooklyn  ...             C
3                           Queens  ...             C
4                    Staten Island  ...             C
17    Mott Haven and Melrose (CD1)  ...             C
...                            ...  ...           ...
6987                     Rockaways  ...             B
6988                 Port Richmond  ...             C
6989        Stapleton - St. George  ...             C
6990                   Willowbrook  ...             C
6991     South Beach - Tottenville  ...             C

[5949 rows x 10 columns]

                           geo_place_name  ... Final Ranking
2                               Manhattan  ...             C
5                Financial District (CD1)  ...             D
6        Greenwich Village and Soho (CD2)  ...             D
7     Lower East Side and Chinatown (CD3)  ...             C
8               Clinton and Chelsea (CD4)  ...             D
...                                   ...  ...           ...
4933                    Chelsea - Clinton  ...             D
4934          Gramercy Park - Murray Hill  ...             D
4935             Greenwich Village - SoHo  ...             D
4936       Union Square - Lower East Side  ...             C
4937                      Lower Manhattan  ...             D

[1043 rows x 10 columns]

In [ ]:
trainset_brooklyn = df[train_columns].loc[(df["geo_borough_name"] != "Brooklyn") ]
testset_brooklyn = df[train_columns].loc[df["geo_borough_name"] == "Brooklyn"]
display(trainset_brooklyn.groupby(by=["Final Ranking"]).count())
display(testset_brooklyn.groupby(by=["Final Ranking"]).count())
display(trainset_brooklyn)
display(testset_brooklyn)

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
B                         257            257  ...         257                   257
C                        3889           3889  ...        3889                  3889
D                          11             11  ...          11                    11

[3 rows x 9 columns]

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
C                        2835           2835  ...        2835                  2835

[1 rows x 9 columns]

                 geo_place_name  ... Final Ranking
0                         Bronx  ...             C
2                     Manhattan  ...             C
3                        Queens  ...             C
4                 Staten Island  ...             C
5      Financial District (CD1)  ...             D
...                         ...  ...           ...
6987                  Rockaways  ...             B
6988              Port Richmond  ...             C
6989     Stapleton - St. George  ...             C
6990                Willowbrook  ...             C
6991  South Beach - Tottenville  ...             C

[4157 rows x 10 columns]

                              geo_place_name  ... Final Ranking
1                                   Brooklyn  ...             C
29         Greenpoint and Williamsburg (CD1)  ...             C
30    Fort Greene and Brooklyn Heights (CD2)  ...             C
31                  Bedford Stuyvesant (CD3)  ...             C
32                            Bushwick (CD4)  ...             C
...                                      ...  ...           ...
3903                 Williamsburg - Bushwick  ...             C
3904                 Williamsburg - Bushwick  ...             C
3905                 Williamsburg - Bushwick  ...             C
3906                 Williamsburg - Bushwick  ...             C
3907                 Williamsburg - Bushwick  ...             C

[2835 rows x 10 columns]

In [ ]:
trainset_bronx = df[train_columns].loc[(df["geo_borough_name"] != "Bronx") ]
testset_bronx = df[train_columns].loc[df["geo_borough_name"] == "Bronx"]
display(trainset_bronx.groupby(by=["Final Ranking"]).count())
display(testset_bronx.groupby(by=["Final Ranking"]).count())
display(trainset_bronx)
display(testset_bronx)

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
B                         257            257  ...         257                   257
C                        5684           5684  ...        5684                  5684
D                          11             11  ...          11                    11

[3 rows x 9 columns]

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
C                        1040           1040  ...        1040                  1040

[1 rows x 9 columns]

                 geo_place_name  ... Final Ranking
1                      Brooklyn  ...             C
2                     Manhattan  ...             C
3                        Queens  ...             C
4                 Staten Island  ...             C
5      Financial District (CD1)  ...             D
...                         ...  ...           ...
6987                  Rockaways  ...             B
6988              Port Richmond  ...             C
6989     Stapleton - St. George  ...             C
6990                Willowbrook  ...             C
6991  South Beach - Tottenville  ...             C

[5952 rows x 10 columns]

                      geo_place_name  ... Final Ranking
0                              Bronx  ...             C
17      Mott Haven and Melrose (CD1)  ...             C
18    Hunts Point and Longwood (CD2)  ...             C
19      Morrisania and Crotona (CD3)  ...             C
20    Highbridge and Concourse (CD4)  ...             C
...                              ...  ...           ...
1087            Pelham - Throgs Neck  ...             C
1088            Pelham - Throgs Neck  ...             C
1089                Crotona -Tremont  ...             C
1090        High Bridge - Morrisania  ...             C
1091        Hunts Point - Mott Haven  ...             C

[1040 rows x 10 columns]

In [ ]:
trainset_queens = df[train_columns].loc[(df["geo_borough_name"] != "Queens") ]
testset_queens = df[train_columns].loc[df["geo_borough_name"] == "Queens"]
display(trainset.groupby(by=["Final Ranking"]).count())
display(testset.groupby(by=["Final Ranking"]).count())
display(trainset_queens)
display(testset_queens)

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
B                         257            257  ...         257                   257
C                        5692           5692  ...        5692                  5692

[2 rows x 9 columns]

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
C                        1032           1032  ...        1032                  1032
D                          11             11  ...          11                    11

[2 rows x 9 columns]

                 geo_place_name  ... Final Ranking
0                         Bronx  ...             C
1                      Brooklyn  ...             C
2                     Manhattan  ...             C
4                 Staten Island  ...             C
5      Financial District (CD1)  ...             D
...                         ...  ...           ...
4937            Lower Manhattan  ...             D
6988              Port Richmond  ...             C
6989     Stapleton - St. George  ...             C
6990                Willowbrook  ...             C
6991  South Beach - Tottenville  ...             C

[4927 rows x 10 columns]

                          geo_place_name  ... Final Ranking
3                                 Queens  ...             C
47    Long Island City and Astoria (CD1)  ...             C
48          Woodside and Sunnyside (CD2)  ...             C
49                 Jackson Heights (CD3)  ...             C
50             Elmhurst and Corona (CD4)  ...             C
...                                  ...  ...           ...
6983                           Rockaways  ...             B
6984                           Rockaways  ...             B
6985                           Rockaways  ...             B
6986                           Rockaways  ...             B
6987                           Rockaways  ...             B

[2065 rows x 10 columns]

In [ ]:
trainset_st = df[train_columns].loc[(df["geo_borough_name"] != "Staten Island") ]
testset_st = df[train_columns].loc[df["geo_borough_name"] == "Staten Island"]
display(trainset_st.groupby(by=["Final Ranking"]).count())
display(testset_st.groupby(by=["Final Ranking"]).count())
display(trainset_st)
display(testset_st)

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
B                         257            257  ...         257                   257
C                        6719           6719  ...        6719                  6719
D                          11             11  ...          11                    11

[3 rows x 9 columns]

               geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
Final Ranking                                 ...
C                           5              5  ...           5                     5

[1 rows x 9 columns]

                geo_place_name  ... Final Ranking
0                        Bronx  ...             C
1                     Brooklyn  ...             C
2                    Manhattan  ...             C
3                       Queens  ...             C
5     Financial District (CD1)  ...             D
...                        ...  ...           ...
6983                 Rockaways  ...             B
6984                 Rockaways  ...             B
6985                 Rockaways  ...             B
6986                 Rockaways  ...             B
6987                 Rockaways  ...             B

[6987 rows x 10 columns]

                 geo_place_name  ... Final Ranking
4                 Staten Island  ...             C
6988              Port Richmond  ...             C
6989     Stapleton - St. George  ...             C
6990                Willowbrook  ...             C
6991  South Beach - Tottenville  ...             C

[5 rows x 10 columns]

In [ ]:
trainset = trainset_bronx
testset = testset_bronx

In [ ]:
display(trainset)
display(testset)

                 geo_place_name  ... Final Ranking
1                      Brooklyn  ...             C
2                     Manhattan  ...             C
3                        Queens  ...             C
4                 Staten Island  ...             C
5      Financial District (CD1)  ...             D
...                         ...  ...           ...
6987                  Rockaways  ...             B
6988              Port Richmond  ...             C
6989     Stapleton - St. George  ...             C
6990                Willowbrook  ...             C
6991  South Beach - Tottenville  ...             C

[5952 rows x 10 columns]

                      geo_place_name  ... Final Ranking
0                              Bronx  ...             C
17      Mott Haven and Melrose (CD1)  ...             C
18    Hunts Point and Longwood (CD2)  ...             C
19      Morrisania and Crotona (CD3)  ...             C
20    Highbridge and Concourse (CD4)  ...             C
...                              ...  ...           ...
1087            Pelham - Throgs Neck  ...             C
1088            Pelham - Throgs Neck  ...             C
1089                Crotona -Tremont  ...             C
1090        High Bridge - Morrisania  ...             C
1091        Hunts Point - Mott Haven  ...             C

[1040 rows x 10 columns]

In [ ]:
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# for column in train_columns:
#     le.fit(df[column])
#     df[column] = le.transform(df[column])

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
frames = [trainset, testset]
df_traintest = pd.concat(frames)
display(df_traintest)
le_name_mapping = {}
for column in ["geo_place_name", "geo_type_name","geo_borough_name", "Final Ranking"]:
    # le.fit(trainset[column])
    # trainset[column] = le.transform(trainset[column])
    # le.fit(testset[column])
    # testset[column] = le.transform(testset[column])

    # le.fit(df[train_columns][column])
    # df[train_columns][column] = le.transform(df[train_columns][column])

    le.fit(df_traintest[column])
    le_name_mapping[column] = dict(zip(le.classes_, le.transform(le.classes_)))
    # print(le_name_mapping)
    df_traintest[column] = le.transform(df_traintest[column])

print(le_name_mapping["geo_borough_name"])
# trainset_bronx = df[train_columns].loc[(df["geo_borough_name"] != "Bronx") ]
# testset_bronx = df[train_columns].loc[df["geo_borough_name"] == "Bronx"]

trainset_bronx = df_traintest.loc[(df_traintest["geo_borough_name"] != le_name_mapping["geo_borough_name"]["Bronx"]) ]
testset_bronx = df_traintest.loc[(df_traintest["geo_borough_name"] == le_name_mapping["geo_borough_name"]["Bronx"]) ]

trainset = trainset_bronx
testset = testset_bronx

X_train = trainset.drop(["Final Ranking"], axis=1)
y_train = trainset["Final Ranking"]

X_test = testset.drop(["Final Ranking"], axis=1)
y_test = testset["Final Ranking"]

print("X_train after encoding")
display(X_train)
print("X_test after encoding")
display(X_test)
print("y_train after encoding")
display(y_train)
print("y_test after encoding")
display(y_test)

from sklearn.preprocessing import StandardScaler

scl = StandardScaler()

X_train = pd.DataFrame(scl.fit_transform(X_train), columns = X_train.columns)
print("X_train after scaling")
display(X_train)

X_test = pd.DataFrame(scl.transform(X_test), columns = X_test.columns)
print("X_test after encoding")
display(X_test)

                geo_place_name  ... Final Ranking
1                     Brooklyn  ...             C
2                    Manhattan  ...             C
3                       Queens  ...             C
4                Staten Island  ...             C
5     Financial District (CD1)  ...             D
...                        ...  ...           ...
1087      Pelham - Throgs Neck  ...             C
1088      Pelham - Throgs Neck  ...             C
1089          Crotona -Tremont  ...             C
1090  High Bridge - Morrisania  ...             C
1091  Hunts Point - Mott Haven  ...             C

[6992 rows x 10 columns]

{'Bronx': 0, 'Brooklyn': 1, 'Manhattan': 2, 'New York City': 3, 'Queens': 4, 'Staten Island': 5, 'Staten Island ': 6}
X_train after encoding

      geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
1                 11              0  ...       66.38                8.5412
2                 60              0  ...       54.54               20.4098
3                 72              0  ...       67.44                8.9604
4                 89              0  ...       68.32                4.6636
5                 31              1  ...       50.46               10.3752
...              ...            ...  ...         ...                   ...
6987              79              3  ...       78.06                4.9780
6988              71              3  ...       62.04                5.4496
6989              88              3  ...       66.34                5.4496
6990             105              3  ...       66.26                4.7946
6991              81              3  ...       71.86                4.0872

[5952 rows x 9 columns]

X_test after encoding

      geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
0                 10              0  ...       65.82               14.2528
17                65              1  ...       64.24               12.9166
18                49              1  ...       67.54               11.5280
19                64              1  ...       63.74               15.5890
20                46              1  ...       61.66               23.0036
...              ...            ...  ...         ...                   ...
1087              70              3  ...       68.48               11.1874
1088              70              3  ...       68.48               11.1874
1089              21              3  ...       62.92               20.4098
1090              45              3  ...       62.24               19.9644
1091              48              3  ...       66.84               11.7900

[1040 rows x 9 columns]

y_train after encoding

1       1
2       1
3       1
4       1
5       2
       ..
6987    0
6988    1
6989    1
6990    1
6991    1
Name: Final Ranking, Length: 5952, dtype: int64

y_test after encoding

0       1
17      1
18      1
19      1
20      1
       ..
1087    1
1088    1
1089    1
1090    1
1091    1
Name: Final Ranking, Length: 1040, dtype: int64

X_train after scaling

      geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
0          -1.149643     -15.403364  ...    0.242058             -0.481647
1           0.257742     -15.403364  ...   -2.201195              1.863414
2           0.602407     -15.403364  ...    0.460795             -0.398819
3           1.090684     -15.403364  ...    0.642388             -1.247803
4          -0.575201     -10.237956  ...   -3.043127             -0.119275
...              ...            ...  ...         ...                   ...
5947        0.803462       0.092859  ...    2.652294             -1.185682
5948        0.573685       0.092859  ...   -0.653527             -1.092501
5949        1.061962       0.092859  ...    0.233803             -1.092501
5950        1.550238       0.092859  ...    0.217295             -1.221920
5951        0.860907       0.092859  ...    1.372888             -1.361691

[5952 rows x 9 columns]

X_test after encoding

      geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
0          -1.178366     -15.403364  ...    0.126498              0.646881
1           0.401352     -10.237956  ...   -0.199544              0.382868
2          -0.058202     -10.237956  ...    0.481430              0.108501
3           0.372630     -10.237956  ...   -0.302722              0.910895
4          -0.144368     -10.237956  ...   -0.731942              2.375910
...              ...            ...  ...         ...                   ...
1035        0.544963       0.092859  ...    0.675405              0.041203
1036        0.544963       0.092859  ...    0.675405              0.041203
1037       -0.862422       0.092859  ...   -0.471934              1.863414
1038       -0.173090       0.092859  ...   -0.612256              1.775409
1039       -0.086924       0.092859  ...    0.336981              0.160268

[1040 rows x 9 columns]

In [ ]:
X_train.head()

   geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
0       -1.149643     -15.403364  ...    0.242058             -0.481647
1        0.257742     -15.403364  ...   -2.201195              1.863414
2        0.602407     -15.403364  ...    0.460795             -0.398819
3        1.090684     -15.403364  ...    0.642388             -1.247803
4       -0.575201     -10.237956  ...   -3.043127             -0.119275

[5 rows x 9 columns]

In [ ]:
X_test.head()

   geo_place_name  geo_type_name  ...  Ozone (O3)  Sulfur Dioxide (SO2)
0       -1.178366     -15.403364  ...    0.126498              0.646881
1        0.401352     -10.237956  ...   -0.199544              0.382868
2       -0.058202     -10.237956  ...    0.481430              0.108501
3        0.372630     -10.237956  ...   -0.302722              0.910895
4       -0.144368     -10.237956  ...   -0.731942              2.375910

[5 rows x 9 columns]

In [ ]:
y_train.head()

1    1
2    1
3    1
4    1
5    2
Name: Final Ranking, dtype: int64

In [ ]:
y_train.unique()

array([1, 2, 0])

In [ ]:
y_test.head()

0     1
17    1
18    1
19    1
20    1
Name: Final Ranking, dtype: int64

In [ ]:
y_test.unique()

array([1])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_validate
from sklearn import metrics
from sklearn.metrics import f1_score
from numpy import mean

lrm = LogisticRegression()
dtm = DecisionTreeClassifier(random_state=0, max_depth=5)
gnbm = GaussianNB()

models = [lrm, dtm, gnbm]
score_lst = []
mean_score_lst = []

for m in models:
    # scores = cross_validate(m, X_train, y_train, scoring = ['accuracy','precision','recall','f1'], cv=5)
    #scores = cross_validate(m, X_train, y_train, scoring = ['accuracy','precision_macro','recall_macro','f1_macro'], cv=5)
    scores = cross_validate(m, X_train, y_train, scoring = ['accuracy','precision_weighted','recall_weighted','f1_weighted'], cv=5)
    scores = pd.DataFrame(scores)
    score_lst.append(scores.drop(['fit_time', 'score_time'], axis = 1))
    mean_score = pd.DataFrame(scores.mean()).drop(index = ['fit_time', 'score_time'])
    mean_score_lst.append(mean_score)

In [ ]:
display('Logistic Regression performance on 5 folds is:', '\n')
score_lst[0]

'Logistic Regression performance on 5 folds is:'

'\n'

   test_accuracy  ...  test_f1_weighted
0       0.996641  ...          0.997182
1       1.000000  ...          1.000000
2       0.999160  ...          0.999020
3       0.999160  ...          0.999020
4       0.997479  ...          0.997063

[5 rows x 4 columns]

In [ ]:
display('Logistic Regression Mean performance on 5 folds is:', '\n')
mean_score_lst[0]

'Logistic Regression Mean performance on 5 folds is:'

'\n'

                                0
test_accuracy            0.998488
test_precision_weighted  0.998797
test_recall_weighted     0.998488
test_f1_weighted         0.998457

In [ ]:
display('Decision Tree performance on 5 folds is:', '\n')
score_lst[1]

'Decision Tree performance on 5 folds is:'

'\n'

   test_accuracy  ...  test_f1_weighted
0        0.99916  ...          0.999244
1        1.00000  ...          1.000000
2        1.00000  ...          1.000000
3        1.00000  ...          1.000000
4        1.00000  ...          1.000000

[5 rows x 4 columns]

In [ ]:
display('Decision Tree Mean performance on 5 folds is:', '\n')
mean_score_lst[1]

'Decision Tree Mean performance on 5 folds is:'

'\n'

                                0
test_accuracy            0.999832
test_precision_weighted  0.999888
test_recall_weighted     0.999832
test_f1_weighted         0.999849

In [ ]:
display('Naive Bayes performance on 5 folds is:', '\n')
score_lst[2]

'Naive Bayes performance on 5 folds is:'

'\n'

   test_accuracy  ...  test_f1_weighted
0       0.961377  ...          0.978758
1       1.000000  ...          1.000000
2       0.569748  ...          0.720695
3       0.784034  ...          0.876603
4       1.000000  ...          1.000000

[5 rows x 4 columns]

In [ ]:
display('Naive Bayes Mean performance on 5 folds is:', '\n')
mean_score_lst[2]

'Naive Bayes Mean performance on 5 folds is:'

'\n'

                                0
test_accuracy            0.863032
test_precision_weighted  0.999010
test_recall_weighted     0.863032
test_f1_weighted         0.915211

In [ ]:
lrm.fit(X_train, y_train)
y_pred = lrm.predict(X_test)
print(type(y_pred))
display(set(y_pred))
display(y_pred[:5])
report = metrics.classification_report(y_test, y_pred, output_dict=True)
df_classification_report = pd.DataFrame(report).transpose()

unique, counts = np.unique(y_pred, return_counts=True)

print(np.asarray((unique, counts)).T)
display(report)
display(df_classification_report)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('Accuracy score: {}'.format(accuracy_score(y_test, y_pred)))
print('Precision score: {}'.format(precision_score(y_test, y_pred)))
print('Recall score: {}'.format(recall_score(y_test, y_pred)))
print('F1 score: {}'.format(f1_score(y_test, y_pred)))

print(metrics.classification_report(y_test, y_pred))

<class 'numpy.ndarray'>

{1}

array([1, 1, 1, 1, 1])

[[   1 1040]]

{'1': {'f1-score': 1.0, 'precision': 1.0, 'recall': 1.0, 'support': 1040},
 'accuracy': 1.0,
 'macro avg': {'f1-score': 1.0,
  'precision': 1.0,
  'recall': 1.0,
  'support': 1040},
 'weighted avg': {'f1-score': 1.0,
  'precision': 1.0,
  'recall': 1.0,
  'support': 1040}}

              precision  recall  f1-score  support
1                   1.0     1.0       1.0   1040.0
accuracy            1.0     1.0       1.0      1.0
macro avg           1.0     1.0       1.0   1040.0
weighted avg        1.0     1.0       1.0   1040.0

Accuracy score: 1.0
Precision score: 1.0
Recall score: 1.0
F1 score: 1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1040

    accuracy                           1.00      1040
   macro avg       1.00      1.00      1.00      1040
weighted avg       1.00      1.00      1.00      1040

In [ ]:
dtm.fit(X_train, y_train)
y_pred = dtm.predict(X_test)
report = metrics.classification_report(y_test, y_pred, output_dict=True)
df_classification_report = pd.DataFrame(report).transpose()

unique, counts = np.unique(y_pred, return_counts=True)

print(np.asarray((unique, counts)).T)
df_classification_report

[[   1 1040]]

              precision  recall  f1-score  support
1                   1.0     1.0       1.0   1040.0
accuracy            1.0     1.0       1.0      1.0
macro avg           1.0     1.0       1.0   1040.0
weighted avg        1.0     1.0       1.0   1040.0

In [ ]:
gnbm.fit(X_train, y_train)
y_pred = gnbm.predict(X_test)
report = metrics.classification_report(y_test, y_pred, output_dict=True)
df_classification_report = pd.DataFrame(report).transpose()

unique, counts = np.unique(y_pred, return_counts=True)

print(np.asarray((unique, counts)).T)
df_classification_report

[[   1 1040]]

              precision  recall  f1-score  support
1                   1.0     1.0       1.0   1040.0
accuracy            1.0     1.0       1.0      1.0
macro avg           1.0     1.0       1.0   1040.0
weighted avg        1.0     1.0       1.0   1040.0

In [ ]:
#!apt-get -qq install texlive texlive-xetex texlive-latex-extra pandoc 
#!pip install --quiet pypandoc

In [ ]:
#!jupyter nbconvert --to PDF "/content/drive/MyDrive/Masters/VTech Subjects/CS 5834 Intro to Urban Computing/Project/code/Urban_project_4.ipynb"